// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package tagsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :exec
INSERT INTO tags (id, name, created_at) VALUES ($1, $2, $3)
`

type CreateTagParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.Exec(ctx, createTag, arg.ID, arg.Name, arg.CreatedAt)
	return err
}
