// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package tagsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :exec
INSERT INTO tags (id, name, created_at) VALUES ($1, $2, $3)
`

type CreateTagParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.Exec(ctx, createTag, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
