// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package mediadb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachTag = `-- name: AttachTag :exec
INSERT INTO media_tags (media_id, tag_id) VALUES ($1, $2)
`

type AttachTagParams struct {
	MediaID uuid.UUID
	TagID   uuid.UUID
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.MediaID, arg.TagID)
	return err
}

const createMedia = `-- name: CreateMedia :exec
INSERT INTO media (id, name, file_key, content_type, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMediaParams struct {
	ID          uuid.UUID
	Name        string
	FileKey     string
	ContentType string
	CreatedAt   time.Time
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) error {
	_, err := q.db.Exec(ctx, createMedia,
		arg.ID,
		arg.Name,
		arg.FileKey,
		arg.ContentType,
		arg.CreatedAt,
	)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, name, file_key, content_type, created_at
FROM media
WHERE id = $1
`

// Fetches the metadata of a single media.
func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Media, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FileKey,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const listTagsByMediaID = `-- name: ListTagsByMediaID :many
SELECT t.id, t.name, t.created_at
FROM tags t
JOIN media_tags mt ON mt.tag_id = t.id
WHERE mt.media_id = $1
ORDER BY t.name ASC
`

// Returns every tag attached to the given media, ordered by name so
// the API response is deterministic.
func (q *Queries) ListTagsByMediaID(ctx context.Context, mediaID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsExist = `-- name: TagsExist :many
SELECT id FROM tags WHERE id = ANY($1::uuid[])
`

func (q *Queries) TagsExist(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, tagsExist, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
