// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mediadb

import (
	"time"

	"github.com/google/uuid"
)

type Media struct {
	ID          uuid.UUID
	Name        string
	FileKey     string
	ContentType string
	CreatedAt   time.Time
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}
